figure(1,'name','mu:baseline tests(idle states)');
figure(2,'name','mu:baseline tests(idle states) time patterns');
figure(3,'name','mu:c3');
figure(4,'name','mu:c3 time patterns');
figure(5,'name','gamma:baseline tests(idle states)');
figure(6,'name','gamma:baseline tests(idle states) time patterns');
figure(7,'name','gamma:all tasks');
figure(8,'name','gamma:all tasks time patterns');
figure(9,'name','mu:cz');
figure(10,'name','mu:cz time patterns');
figure(11,'name','mu:c4');
figure(12,'name','mu:c4 time patterns');
